### ISSUE TITLE
大佬请教一下，我修改了toolchain.cmake 中sdcc的路径，路径修改对了，但是编译时使用的还是vs，这是咋回事呢？

### ISSUE THREAD

**Issue by durongze** [peitianyu/sdcc_stc_example#1]
我加了message ，输出显示的路径是对的。但是check的时候，还是check到了本地的vs。

[INFO] CMAKE_FIND_ROOT_PATH : F:/Program/SDCC
[INFO] CMAKE_C_COMPILER     : F:/Program/SDCC/bin/sdcc.exe
[INFO] CMAKE_CXX_COMPILER   : F:/Program/SDCC/bin/sdcpp.exe
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info

**Comment by peitianyu** [comment]
看起来也挺不错的

**Comment by peitianyu** [comment]
你用什么系统编译的呀！我是用wsl，ubuntu做的

**Comment by durongze** [comment]
> 你用什么系统编译的呀！我是用wsl，ubuntu做的

我用windows，windows10不可以吗？

**Comment by durongze** [comment]
> 看起来也挺不错的

为啥它自动检测到了我c盘的vs呢？

**Comment by durongze** [comment]
会不会是因为没有运行cppcheck命令？windows下没有执行 cppcheck也没有什么影响吧

**Comment by durongze** [comment]
> 你用什么系统编译的呀！我是用wsl，ubuntu做的

我也试过了，linux确实是可以，但是windows下不行呢。总是自动检测vs。

**Comment by peitianyu** [comment]
> > 你用什么系统编译的呀！我是用wsl，ubuntu做的
> 
> 我用windows，windows10不可以吗？

按理说可以的，好像keil也可以通过这种方式做，不过我没做，所以不太清楚了

**Comment by peitianyu** [comment]
> > 看起来也挺不错的
> 
> 为啥它自动检测到了我c盘的vs呢？

这个我就不清楚了

**Comment by peitianyu** [comment]
> 会不会是因为没有运行cppcheck命令？windows下没有执行 cppcheck也没有什么影响吧
> 
这个主要用于检测单片机有没有没使用的函数，可以把这个去掉试试

**Comment by durongze** [comment]
多谢。
